# Generated by Django 5.2.6 on 2026-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code for avatar background (e.g., #10b981)",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(
                blank=True,
                help_text="URL or path to profile image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
