# Generated by Django 5.2.6 on 2026-02-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_color_user_profile_image_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("avatar_color", models.CharField(blank=True, max_length=7, null=True)),
                ("otp", models.CharField(max_length=6)),
                ("otp_created_at", models.DateTimeField(auto_now_add=True)),
                ("otp_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pending Registration",
                "verbose_name_plural": "Pending Registrations",
                "db_table": "pending_registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
