# Generated by Django 5.2.6 on 2026-02-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_pendingregistration_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar_color", models.CharField(blank=True, max_length=7, null=True)),
                ("otp", models.CharField(max_length=6)),
                ("otp_created_at", models.DateTimeField(auto_now_add=True)),
                ("otp_attempts", models.IntegerField(default=0)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("registration", "Registration"), ("login", "Login")],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Phone OTP",
                "verbose_name_plural": "Phone OTPs",
                "db_table": "phone_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Phone number with country code (e.g., +1234567890)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
