# Generated by Django 5.2.6 on 2026-02-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_phoneotp_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingregistration",
            name="profile_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
